# Generated by Django 4.1.7 on 2023-03-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_text', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('director', models.CharField(max_length=200)),
                ('imdb_score', models.FloatField(default=0.0)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
