# Generated by Django 4.1.7 on 2023-03-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('star_sign', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('star_sign', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_text', models.CharField(max_length=200)),
                ('release_date', models.IntegerField(default=2023)),
                ('imdb_score', models.FloatField(default=0.0)),
                ('votes', models.IntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryset.director')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.IntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryset.director')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryset.movie')),
            ],
        ),
    ]
